### ISSUE TITLE
Python 3: Determine fate of *pexpect files

### ISSUE THREAD

**Issue by josephsnyder** [OSEHRA/VistA#119]
Determine if we are going to maintain a copy of the pexpect and winpexpect python files in the OSEHRA VistA repository.  If so, ready the files for python 3

If not: determine the pip packages that should be installed for the system to work correctly

**Comment by shabiel** [comment]
My vote is to take these away, as they don't update anymore. Use pip
instead.

**Comment by josephsnyder** [comment]
Files were removed and PIP install command were added as replacements: https://github.com/OSEHRA/VistA/pull/133
