### ISSUE TITLE
Ubuntu autoInstaller breaks

### ISSUE THREAD

**Issue by jssuttles** [OSEHRA/VistA#254]
This line does not actually block an installation without one of these 3 DBs.
https://github.com/OSEHRA/VistA/blob/303a301ef30bfc3df6f33f61b1477d4bd2b9430d/Scripts/Install/Ubuntu/autoInstaller.sh#L162

I think the intention of this line is to block execution if one of these 3 DBs is not included. (This is not documented.) For some reason, this line does not work as I would expect either. If it were to work as I expect, then it would block if GT.M is not included because` ! $installgtm || ! $cacheinstallerpath` is true if $installgtm regardless of whether or not $cacheinstallerpath is included. So, something bash related is wrong here. Then, the logic is not what I would expect. These should be ANDs instead of ORs. If they were ANDs, then `if NOT installgtm AND NOT cacheinstallerpath AND NOT installYottaDB` would be true and would lead to the next statement running and breaking execution.

This causes issues down the line:
```
# Install GT.M or YottaDB
if $installgtm; then
    cd GTM
    if $bootstrap; then
        ./install.sh
    else
        ./install.sh -s
    fi
    # Create the VistA instance
    if $bootstrap; then
        ./createVistaInstance.sh -i $instance
    else
        ./createVistaInstance.sh -i $instance -f
    fi
fi

if $installYottaDB; then
    cd GTM
    if $bootstrap; then
        ./install.sh -y
    else
        ./install.sh -s -y
    fi
    # Create the VistA instance
    if $bootstrap; then
        ./createVistaInstance.sh -i $instance -y
    else
        ./createVistaInstance.sh -i $instance -f -y
    fi
fi

# Install Caché if requested
if $cacheinstallerpath; then
    echo "Cache installer path:" $cacheinstallerpath
fi

# Modify the primary user to be able to use the VistA instance
usermod -a -G $instance $primaryuser
chmod g+x /home/$instance
```
usermod relies on createVistaInstance to have created the instance user
\* So, really if cacheinstallerpath is used, then it will also break, I think.

**Comment by shabiel** [comment]
Jason,

We don't really use this script much anymore. We have been maintaining
a copy of this for automated docker images on docker hub. While we
don't test it on VM's often (Joe is off today and can reply on Monday
on this experiences), we are willing to support that use case.

Here's the currently maintained script:
https://github.com/OSEHRA/docker-vista/blob/master/autoInstaller.sh

--Sam

**Comment by jssuttles** [comment]
Thanks! I'll look into using that.
